[connections.supabase]
SUPABASE_URL = "https://mcbbjvjezbgekbmcajii.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYmJqdmplemJnZWtibWNhamlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODE3MzEsImV4cCI6MjA3NTA1NzczMX0.oFYzF9FeUtEUqfV85dSwyoC_y3IFKwxB_1zHh9UZDU8"